#!/usr/bin/env python3
"""Regenerate docs/includes/home-browse.md for the site landing page."""
from __future__ import annotations

import html
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "tools"))

from essay_catalog import (  # noqa: E402
    collect_essays,
    group_essays,
    load_config,
    write_if_changed,
)

OUT = REPO_ROOT / "docs" / "includes" / "home-browse.md"


def md_to_href(path: str) -> str:
    """Convert a docs-relative .md path to a MkDocs site URL (no .md)."""
    href = path.strip().lstrip("/")
    if href.endswith("/index.md"):
        href = href[: -len("index.md")]
    elif href.endswith(".md"):
        href = href[: -len(".md")] + "/"
    elif not href.endswith("/"):
        href += "/"
    return href


def card(path: str, title: str, summary: str, *, compact: bool = False) -> str:
    cls = "home-card home-card--compact" if compact else "home-card"
    href = md_to_href(path)
    return (
        f'<a class="{cls}" href="{html.escape(href)}">'
        f'<span class="home-card__title">{html.escape(title)}</span>'
        f'<span class="home-card__summary">{html.escape(summary)}</span>'
        f"</a>"
    )


def main() -> int:
    cfg = load_config()
    essays = collect_essays(cfg)
    grouped = group_essays(essays, cfg)

    lines: list[str] = [
        "<!-- Generated by tools/gen_home_browse.py — do not edit by hand. -->",
        "",
        '<div class="home-browse" markdown="0">',
        "",
        '<section class="home-section">',
        '<h2 class="home-section__title">Minibooks</h2>',
        '<div class="home-grid home-grid--books">',
    ]
    for item in cfg.get("minibooks") or []:
        lines.append(card(item["path"], item["title"], item["summary"]))
    lines.extend(
        [
            "</div>",
            "</section>",
            "",
            '<section class="home-section">',
            '<h2 class="home-section__title">Essays</h2>',
        ]
    )
    for category, items in grouped:
        lines.append('<div class="home-essay-row">')
        lines.append(
            f'<h3 class="home-essay-row__title">{html.escape(category)}</h3>'
        )
        lines.append('<div class="home-grid home-grid--essays">')
        for e in items:
            lines.append(
                card(f"essays/{e.link}", e.title, e.summary, compact=True)
            )
        lines.append("</div>")
        lines.append("</div>")
    lines.extend(
        [
            "</section>",
            "",
            '<section class="home-section">',
            '<h2 class="home-section__title">Incidents</h2>',
            '<div class="home-grid home-grid--incidents">',
        ]
    )
    for item in cfg.get("incidents") or []:
        lines.append(card(item["path"], item["title"], item["summary"]))
    lines.extend(
        [
            "</div>",
            "</section>",
            "",
            '<section class="home-section">',
            '<h2 class="home-section__title">Whoami</h2>',
            '<div class="home-grid home-grid--whoami">',
        ]
    )
    for item in cfg.get("whoami") or cfg.get("about") or []:
        lines.append(card(item["path"], item["title"], item["summary"]))
    lines.extend(["</div>", "</section>", "", "</div>", ""])

    text = "\n".join(lines)
    write_if_changed(OUT, text, f"{len(essays)} essays")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
